export const METERS_PER_DEGREE_LATITUDE = 110_540;
export const METERS_PER_DEGREE_LONGITUDE_AT_EQUATOR = 111_320;

export const MAP_SCENE_GROUND_MARGIN = 120;
export const MAP_SCENE_GRID_DIVISIONS = 180;
export const MAP_SCENE_GRID_PRIMARY_COLOR = 0x3a4556;
export const MAP_SCENE_GRID_SECONDARY_COLOR = 0x2a3546;
export const MAP_SCENE_GRID_OPACITY = 0.45;

export const MAP_SCENE_OUTER_MASK_WORLD_SIZE = 20_000;
export const MAP_SCENE_OUTER_MASK_COLOR = 0x0a1420;
export const MAP_SCENE_OUTER_MASK_OPACITY = 0.85;
export const MAP_SCENE_OUTER_MASK_Y = 0.2;
