import {
  approachDirectionForHeading,
  assignCoordinatedSignalOffsets,
  buildSignalTimingPlan,
  canVehicleProceed,
  createSignalApproachDemand,
  createSignalApproachDistance,
  createSignalAxisOccupancy,
  createSignalData,
  createSignalDirectionalOccupancy,
  createSignalTurnDemand,
  dominantAxis,
  dominantAxisForHeading,
  normalizeSignalOffset,
  opposingSignalDirection,
  preferredSignalAxisForApproaches,
  pushSignalPhase,
  resetSignalApproachDemand,
  resetSignalApproachDistance,
  resetSignalAxisOccupancy,
  resetSignalDirectionalOccupancy,
  resetSignalTurnDemand,
  signalAxisForDirection,
  signalAxisPresence,
  signalDirectionForVector,
  SIGNAL_FLOW_CLEARANCE,
  SIGNAL_FLOW_EW_GREEN,
  SIGNAL_FLOW_EW_LEFT,
  SIGNAL_FLOW_EW_YELLOW,
  signalFlowForAxis,
  SIGNAL_FLOW_NS_GREEN,
  SIGNAL_FLOW_NS_LEFT,
  SIGNAL_FLOW_NS_YELLOW,
  SIGNAL_FLOW_PED_FLASH,
  SIGNAL_FLOW_PED_WALK,
  signalState,
  signalVectorForDirection,
} from "@/components/map-simulator/signal-controller";
import {
  addVehicleSampleToBucket,
  buildCumulative,
  buildSegmentHeadings,
  buildSegmentLengthsFromCumulative,
  clampRouteDistance,
  clearVehicleSampleBuckets,
  copyVehicleMotionState,
  createNextStopState,
  createRouteSample,
  createVehicleMotionState,
  createVehicleSimulationSample,
  curbsideApproachBlend,
  curbsideLaneOffset,
  dampAngle,
  distanceXZ,
  normalizeDistance,
  offsetToRight,
  polygonAreaXZ,
  resolveNextStop,
  resolveNextStopInto,
  routeDistanceAhead,
  routeSegmentIndexAtDistance,
  sampleRoute,
  sampleRouteInto,
  syncVehicleSampleBucket,
  vehicleProximityCellCoord,
  wrapAngle,
  writeRightVector,
} from "@/components/map-simulator/route-motion-utils";
import { DEFAULT_MAP_CENTER } from "@/components/map-simulator/map-defaults";
import {
  buildProjectedRoadSegments,
  buildRoadSegmentSpatialIndex,
  collectRoadSegmentCandidateIndices,
  featureCollectionCenter,
  geoKey,
  lineStringsOfRoad,
  outerRingOfBuilding,
  outerRingsOfDong,
  projectPoint,
  roadSegmentCellCoord,
  shapeFromPolygonCoordinates,
  shapePointsFromCoordinates,
  shapesOfNonRoadFeature,
  visitGeometryPositions,
} from "@/components/map-simulator/map-geometry-utils";
export { DEFAULT_MAP_CENTER };
export {
  DEFAULT_CAMERA_PITCH_CONTROL_VALUE,
  DEFAULT_CAMERA_YAW_CONTROL_VALUE,
} from "@/components/map-simulator/camera-types";
export type {
  BaseCameraMode,
  CameraFocusTarget,
  CameraMode,
  CameraPitchControlState,
  CameraYawControlState,
  FpsMode,
} from "@/components/map-simulator/camera-types";
export {
  DEFAULT_TAXI_COUNT,
  DEFAULT_TRAFFIC_COUNT,
  MAX_TAXI_COUNT,
  MAX_TRAFFIC_COUNT,
  MIN_TAXI_COUNT,
  MIN_TRAFFIC_COUNT,
} from "@/components/map-simulator/simulation-defaults";
export {
  PANEL_ACCENT_CARD_CLASS,
  PANEL_CARD_CLASS,
  PANEL_CARD_COMPACT_CLASS,
  PANEL_EYEBROW_CLASS,
  PANEL_INSET_CLASS,
  PANEL_INSET_PADDED_CLASS,
  PANEL_SECTION_LABEL_CLASS,
  PANEL_STATUS_TILE_CLASS,
  PANEL_TOKEN_CLASS,
  panelSelectableClass,
} from "@/components/map-simulator/panel-classes";
export {
  approachDirectionForHeading,
  addVehicleSampleToBucket,
  assignCoordinatedSignalOffsets,
  buildCumulative,
  buildSignalTimingPlan,
  buildSegmentHeadings,
  buildSegmentLengthsFromCumulative,
  buildProjectedRoadSegments,
  buildRoadSegmentSpatialIndex,
  canVehicleProceed,
  clampRouteDistance,
  clearVehicleSampleBuckets,
  collectRoadSegmentCandidateIndices,
  copyVehicleMotionState,
  createNextStopState,
  createRouteSample,
  createSignalApproachDemand,
  createSignalApproachDistance,
  createSignalAxisOccupancy,
  createSignalData,
  createSignalDirectionalOccupancy,
  createSignalTurnDemand,
  createVehicleMotionState,
  createVehicleSimulationSample,
  curbsideApproachBlend,
  curbsideLaneOffset,
  dampAngle,
  distanceXZ,
  dominantAxis,
  dominantAxisForHeading,
  featureCollectionCenter,
  geoKey,
  lineStringsOfRoad,
  normalizeDistance,
  normalizeSignalOffset,
  offsetToRight,
  opposingSignalDirection,
  outerRingOfBuilding,
  outerRingsOfDong,
  polygonAreaXZ,
  preferredSignalAxisForApproaches,
  projectPoint,
  pushSignalPhase,
  resolveNextStop,
  resolveNextStopInto,
  resetSignalApproachDemand,
  resetSignalApproachDistance,
  resetSignalAxisOccupancy,
  resetSignalDirectionalOccupancy,
  resetSignalTurnDemand,
  roadSegmentCellCoord,
  routeDistanceAhead,
  routeSegmentIndexAtDistance,
  sampleRoute,
  sampleRouteInto,
  shapeFromPolygonCoordinates,
  shapePointsFromCoordinates,
  shapesOfNonRoadFeature,
  signalAxisForDirection,
  signalAxisPresence,
  signalDirectionForVector,
  SIGNAL_FLOW_CLEARANCE,
  SIGNAL_FLOW_EW_GREEN,
  SIGNAL_FLOW_EW_LEFT,
  SIGNAL_FLOW_EW_YELLOW,
  signalFlowForAxis,
  SIGNAL_FLOW_NS_GREEN,
  SIGNAL_FLOW_NS_LEFT,
  SIGNAL_FLOW_NS_YELLOW,
  SIGNAL_FLOW_PED_FLASH,
  SIGNAL_FLOW_PED_WALK,
  signalState,
  signalVectorForDirection,
  syncVehicleSampleBucket,
  vehicleProximityCellCoord,
  visitGeometryPositions,
  wrapAngle,
  writeRightVector,
};
export {
  EMPTY_NON_ROAD_FEATURE_COLLECTION,
  EMPTY_TAXI_STAND_FEATURE_COLLECTION,
  EMPTY_TRAFFIC_SIGNAL_FEATURE_COLLECTION,
} from "@/components/map-simulator/empty-feature-collections";
export type * from "@/components/map-simulator/map-simulator-types";
