/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect } from "react";
import {
  createMapSimulatorEngine,
  type MapSimulatorSceneRuntimeProps,
} from "@/components/map-simulator/engine/simulator-engine";

export type { MapSimulatorSceneRuntimeProps };

export default function MapSimulatorSceneRuntime({
  containerRef,
  data,
  poiFeatureRowsRef,
  onPoiSelect,
  onDongSelect,
  appliedTaxiCountRef,
  appliedTrafficCountRef,
  selectedDemandDongRef,
  hasDemandDataRef,
  selectedDemandScoreRef,
  currentFiveMinuteDemandRef,
  currentDemandVisualUnitsRef,
  cameraModeRef,
  followTaxiIdRef,
  rideExitModeRef,
  showLabelsRef,
  optionalLabelObjectsRef,
  showTransitRef,
  transitGroupRef,
  hoverRefreshRequestRef,
  labelRefreshRequestRef,
  fpsModeRef,
  showNonRoadRef,
  nonRoadGroupRef,
  showRoadNetworkRef,
  roadNetworkGroupRef,
  cameraFocusTargetRef,
  simulationDateRef,
  simulationTimeRef,
  weatherModeRef,
  cameraPitchControlRef,
  cameraYawControlRef,
  setStatus,
  setStatusDetail,
  setLoadingProgress,
  setStats,
  setFollowTaxiId,
  setCameraMode,
  onCameraFocusChange,
}: MapSimulatorSceneRuntimeProps) {
  useEffect(() => {
    return createMapSimulatorEngine({
      containerRef,
      data,
      poiFeatureRowsRef,
      onPoiSelect,
      onDongSelect,
      appliedTaxiCountRef,
      appliedTrafficCountRef,
      selectedDemandDongRef,
      hasDemandDataRef,
      selectedDemandScoreRef,
      currentFiveMinuteDemandRef,
      currentDemandVisualUnitsRef,
      cameraModeRef,
      followTaxiIdRef,
      rideExitModeRef,
      showLabelsRef,
      optionalLabelObjectsRef,
      showTransitRef,
      transitGroupRef,
      hoverRefreshRequestRef,
      labelRefreshRequestRef,
      fpsModeRef,
      showNonRoadRef,
      nonRoadGroupRef,
      showRoadNetworkRef,
      roadNetworkGroupRef,
      cameraFocusTargetRef,
      simulationDateRef,
      simulationTimeRef,
      weatherModeRef,
      cameraPitchControlRef,
      cameraYawControlRef,
      setStatus,
      setStatusDetail,
      setLoadingProgress,
      setStats,
      setFollowTaxiId,
      setCameraMode,
      onCameraFocusChange,
    });
  }, [
    appliedTaxiCountRef,
    appliedTrafficCountRef,
    cameraModeRef,
    cameraPitchControlRef,
    cameraYawControlRef,
    currentDemandVisualUnitsRef,
    currentFiveMinuteDemandRef,
    data,
    fpsModeRef,
    followTaxiIdRef,
    hasDemandDataRef,
    poiFeatureRowsRef,
    selectedDemandDongRef,
    selectedDemandScoreRef,
    showLabelsRef,
    showNonRoadRef,
    showRoadNetworkRef,
    showTransitRef,
    simulationDateRef,
    simulationTimeRef,
    weatherModeRef,
  ]);

  return null;
}
